# Generated by Django 4.1 on 2022-08-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/albums'),
        ),
        migrations.AlterField(
            model_name='song',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Remix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=100)),
                ('artists', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('file_128', models.FileField(blank=True, null=True, upload_to='songs')),
                ('file_320', models.FileField(blank=True, null=True, upload_to='songs')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images')),
                ('text', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
