# Generated by Django 4.1 on 2022-09-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_album_cover_alter_song_text_remix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remix',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='song',
            name='suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='remix',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/remixes'),
        ),
    ]
